### ISSUE TITLE
Support for nested directories

### ISSUE THREAD

**Issue by ChemaCLi** [xpol/cypress-template-fixtures#1]
Hi there. The module was very helpful for my team! But there is a little problem with nested directories.

We have some nested directories to keep some fixtures organized. By doing so, the `cypress-template-fixtures`will try to run
```
mkdir 'cypress/fixtures.out/first-level/second-level'
```
resulting in this error
```
We invoked the function exported by /.../cypress/plugins/index.js, but it threw an error.
```

It would be nice to add support for nested dirs

**Comment by xpol** [comment]
Fixed in 1.0.3.
